obj-y	+=	leds/
obj-y	+=	backlight/
#obj-y	+=	lightsensor/
obj-y	+=	jogball/
obj-y	+=	keypad_qxdm/
obj-y   +=      vibrator/
obj-y   +=      speaker/
# obj-y	+=	usb/
#obj-$(CONFIG_CCI_KB60_GS_WKUP_SRC) 	+= 	gsensor/
obj-y 	+= 	recovery_mode/
obj-y   +=      easy_update/
#motoko
obj-$(CONFIG_CCI_ACCELERATION_SENSOR)	+=	acceleration_sensor/
obj-$(CONFIG_CCI_GEOMAGNETIC_SENSOR)	+=	geomagnetic_sensor/
obj-$(CONFIG_CCI_ORIENTATION_SENSOR)	+=	orientation_sensor/
obj-$(CONFIG_CCI_LIGHT_SENSOR)	+=	light_sensor/
